---
title: "Lab 1: Lab Setup/Parasite Diversity/Microscope Basics"
author: "Grant Foster"
date: "2024-01-08"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Student Learning Outcomes

At the end of this lab, a successful learner should be able to…

1. Describe the overall structure of the laboratory course, expectations for laboratory conduct, and how their grade is assessed
2. Successfully demonstrate how to use a compound light microscope, including loading specimen slides, focusing at multiple magnifications, calculating total magnification, and to accurately measure the size of objects under magnification
3. Label the basic parts of a compound microscope and be able to explain their function
4. Define parasitism (in an ecological sense), identify major parasitic groups of interest, and outline some of the life history strategies lumped together under the term “parasite”
5. Distinguish morphological differences separating major groups of helminth parasites across multiple life stages, and apply that knowledge to identify unknown specimens

## Pre-Lab Materials
Review the course syllabus before coming to lab. In the future, it'll be important to look over this heading before lab this week, as it will contain information you'll need to know for the lab quiz!

## Presentation
[Lab 1 Presentation](Lab1Presentation.pdf)

## Worksheet
[Lab 1 Worksheet](/lab/lab1_diversity/531Lab1Worksheet.docx)

## Resources
