---
title: "Lab 3: Host Range and Parasite Specificity"
author: "Grant Foster"
date: "2024-01-08"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Student Learning Outcomes

At the end of this lab, a successful learner should be able to…

1. Perform the necessary steps to begin analyzing data in the R language (open a development environment, Create a new analysis file, load in analysis packages, load data into the environment). 

2. Create basic linear models in R and interpret their outputs.

3. Create scatter plots and histograms in R and add lines of best fit

4. Describe different ways we can describe levels of parasite host range and explain what types of information these different metrics capture (Number of Hosts, phylogenetic host range, tissue specialization, geographic range, etc). 

5. Describe potential evolutionary tradeoffs between generalist and specialist parasites and evaluate empirical evidence for these tradeoffs. 

6. Define the terms “intensity” and “prevalence” of infections in host populations

7. Summarize takeaways from primary literature supporting and opposing the results of your analysis


## Pre-Lab Materials
Review the course syllabus before coming to lab. In the future, it'll be important to look over this heading before lab this week, as it will contain information you'll need to know for the lab quiz!

## Presentation
[Lab 1 Presentation Stand-in](/lab/lab3_hostRange/Lab1Notes.pdf)

## Worksheet
[Lab 1 Worksheet Stand-in](/lab/lab3_hostRange/531L_Lab1Notes.docx)

## Resources
